---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{.Values.dbmaster.auth.existingSecret}}
data:
  postgres-password: {{.Values.main.db.adminPassword | b64enc}}
  password: {{.Values.main.db.userPassword | b64enc}}
  DATABASE_URL: >
    {{urlJoin (dict "scheme" "jdbc:postgresql"
                    "host" "app-dbmaster:5432"
                    "path" .Values.dbmaster.auth.database
                    "query" (printf "user=%s&password=%s" .Values.dbmaster.auth.username .Values.main.db.userPassword)) | b64enc}}
