---
apiVersion: v1
kind: Service
metadata:
  name: '{{.Release.Name}}-service'
spec:
  type: LoadBalancer
  selector:
    project: {{.Release.Name}}
  ports:
    - name: web-listener
      protocol: TCP
      # Port on Load balancer
      port: 80
      # Port on POD
      targetPort: {{.Values.main.config.PORT}}
