---
apiVersion: v2
name: hs-patients-crud-application
description: Patients CRUD fullstack Clojure(script) application
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    alias: dbmaster
    version: 11.7.1
    repository: https://charts.bitnami.com/bitnami
