---
name: On master released

on:
  release:
    types: [released]
    branches: [master]

jobs:
  Base:
    uses: ./.github/workflows/base.yml

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: [Base]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: app.jar

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, tag, and push image to Docker hub
        env:
          USER_REPOSITORY: jonykoch/patients-crud-application
          TAG: ${{github.ref_name}}
        run: |
          echo "Run build command: 'build -t $USER_REPOSITORY:$TAG .'"
          docker build -t $USER_REPOSITORY:$TAG .
          docker push $USER_REPOSITORY:$TAG
