---
name: On master released

on:
  release:
    types: [released]
    branches: [master]

jobs:
  # Base:
  # uses: ./.github/workflows/base.yml

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY_REPOSITORY: jonykoch/patients-crud-application
          TAG: v0.0.2-manual
        run: |
          docker build -t $REGISTRY_REPOSITORY:$TAG .
          docker push $REGISTRY_REPOSITORY:$TAG
